#!/usr/bin/python2.7
from os import system
import socket
import sys
import re
import time
import threading

HOST = "192.168.0.2"
PORT = 8901

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.bind(('',PORT))

#aaa = str('192.168.0.19')
#system("ip rule add from '%s' priority 10 table main" %(aaa))

period = 0

class sending(threading.Thread):
	def run(self):
		f = open("/sys/class/net/wlan0/statistics/rx_bytes",'r')
		filedata = str(f.readlines())
		BYTE = int(re.findall('\d+', filedata)[0])
		BYTE1 = BYTE

		period = 0
		sock.sendto("E:was CONNECTED", (HOST,PORT))

		while True:
		        try:
		                time.sleep(0.5)
		                f = open("/sys/class/net/wlan0/statistics/rx_bytes",'r')
		                filedata = str(f.readlines())
		                BYTE1 = int(re.findall('\d+', filedata)[0])
		                differ = BYTE1 - BYTE
		                BYTE = BYTE1
		                period += 1

		                if differ > 15000:
		                        sock.sendto("T:" + `differ`, (HOST,PORT))
					print(differ)

		                if period == 10:
					system("iw dev wlan0 station dump | grep Station -c > sta.out")
					f = open("sta.out", 'r')
					stadata = str(f.readlines())
					STA = int(re.findall('\d+', stadata)[0])
					sock.sendto("S:" + `STA`, (HOST,PORT))
					period = 0

			except KeyboardInterrupt:
				sys.exit()

class receiving(threading.Thread):
	def run(self):
		while True:
			try:
				data, addr = sock.recvfrom(1024)
				print('%s' %data)
			except KeyboardInterrupt:
				sys.exit()

send = sending()
recv = receiving()

send.start()
recv.start()
